### ISSUE TITLE
Documentation to reflect new event types

### ISSUE THREAD

**Issue by bitoiu** [chzbrgr71/post-msteams#2]
Hey @chzbrgr71 :wave:

Great work with the latest changes, but does the documentation on the readme reflect the latest changes? I didn't see the details about the environment variable you mentioned earlier. It might be just me.

:octocat::heart:

**Comment by chzbrgr71** [comment]
The docs were updated to explain the event type variable. Not sure if they are clear enough, but it is in there.

**Comment by bitoiu** [comment]
I see it @chzbrgr71, my bad 😞 :blush:

:octocat::heart:
